name: Workload Identity Federation through a Service Account検証
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
  workflow_dispatch: #手動実行
jobs:
  job_id:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 2

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'my-project'
        workload_identity_provider: 'projects/74170354433/locations/global/workloadIdentityPools/blogger-helpxlog/providers/github'
        access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/blogger'
        service_account: 'helpxlog@my-project-1734831833913.iam.gserviceaccount.com'
        token_format: 'access_token'
              
    - name: 'Get Blogger data by ID'
      env:
        ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}
      run: |
        echo "ACCESS_TOKEN: $ACCESS_TOKEN"
        curl -H "Authorization: Bearer $ACCESS_TOKEN" \
            "https://www.googleapis.com/blogger/v3/blogs/5234182378575703690"
