name: Direct Workload Identity Federation 検証
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
  workflow_dispatch:
jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 2

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'my-project'
        workload_identity_provider: 'projects/74170354433/locations/global/workloadIdentityPools/github-pool/providers/github'
 
    - name: 'Get Blogger data by ID'
      env:
        AUTH_TOKEN: ${{ steps.auth.outputs.auth_token }}
      run: |
        echo "AUTH_TOKEN: $AUTH_TOKEN"
        curl -H "Authorization: Bearer $AUTH_TOKEN" \
             "https://www.googleapis.com/blogger/v3/blogs/5234182378575703690"
