name: Workload Identity Federation検証
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
  workflow_dispatch: #手動実行
jobs:
  job_id:
    runs-on: ubuntu-latest
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 2
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'my-project'
        workload_identity_provider: 'projects/74170354433/locations/global/workloadIdentityPools/blogger-helpxlog/providers/github'
        # service_account: 'helpxlog@my-project-1734831833913.iam.gserviceaccount.com'
        # token_format: 'access_token'
        access_token_scopes: 'https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/blogger'
        # id_token_include_email: 'true'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 379.0.0'
    - name: 'Get Blogger data by ID'
      run: |
        ACCESS_TOKEN=$(gcloud auth print-access-token)
        echo "access_token: $ACCESS_TOKEN"
        curl -H "Authorization: Bearer $ACCESS_TOKEN" \
             "https://www.googleapis.com/blogger/v3/blogs/5234182378575703690?key=AIzaSyAbNkNtvvShn2Oif0HATo2ndbwfH-sehWY"
             
        curl -H "Authorization: Bearer $ACCESS_TOKEN" \
             "https://www.googleapis.com/blogger/v3/blogs/5234182378575703690/posts"
             
        curl -H "Authorization: Bearer $ACCESS_TOKEN" \
             "https://www.googleapis.com/blogger/v3/blogs/5234182378575703690/posts" \
              -d '{"kind": "blogger#post","blog": {"id": "5234182378575703690"},"title": "A new post","content": "With <b>exciting</b> content..."}'
         
              