name: Insert post to Google Blogger

on:
  push:
    branches: 
    - main
    paths:
    - '**/*.md'
    - '.github/**/*.*'
  workflow_dispatch:

jobs:
  call-blogger-api:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.1'
      - name: Convert Markdown to HTML
        env:
            GITHUB_EVENT_BEFORE: ${{ github.event.before }}
            GITHUB_EVENT_REPOSITORY_URL: ${{ github.event.repository.url}}
        run: |
          set -eux
          sudo apt-get install -y pandoc
          pip install --user pandoc-include

          diff_list=$(git diff --name-only ${GITHUB_EVENT_BEFORE}..HEAD)

          for file in $diff_list; do
            if [[ ${file} != *.md ]]; then
              continue
            fi
            
            dir_name=$(dirname ${file})
            html_dir=${dir_name}/html
            mkdir -p ${html_dir}

            # md -> html変換
            html_file=${html_dir}/$(basename "${file}" .md).html
            pandoc -f markdown -t html "${file}" > ${html_file}

            # img パス置換
            # ./README-images
            # ↓
            # https://github.com/d4y8/learning-labs/blob/main/<MARKDOWN_DIR_PATH>/README-images

            before_path="\.\/README-images"

            after_path="${GITHUB_EVENT_REPOSITORY_URL}/blob/main/${dir_name}/README-images"
            after_path=${after_path//\//\\/}
            after_path=${after_path//./\\.}
            after_path=${after_path//\?/\\\?}

            sed -i 's/'${before_path}'/'${after_path}'/g' ${html_file}

            before_string="\.png\""
            after_string="\.png\?raw=true\""

            sed -i 's/'${before_string}'/'${after_string}'/g' ${html_file}

            cat ${html_file}
            echo ${html_file} >> html.txt
          done

          if [[ -n ${html_file} ]]; then
            git config user.name  "actions-user"
            git config user.email "action@github.com"
            git add .
            git commit -m "Converted Markdown to HTML"
            git push
          fi

      - name: Set up authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Install dependencies
        # run: pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib
        run: pip install google-api-python-client

      - name: Call Blogger API
        env: 
          BLOG_ID: ${{ secrets.BLOG_ID }}
        run: |
          python .github/scripts/blog_post.py
