name: Insert post to Google Blogger

on:
  push:
    branches: 
    - main
    paths:
    - '**/*.md'
    - '.github/**/*.*'
  workflow_dispatch:

jobs:
  call-blogger-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.1'
      - name: Install dependencies
        run: pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib
      - name: Convert Markdown to HTML
        env:
            GITHUB_EVENT_BEFORE: ${{ github.event.before }}
        run: |
          sudo apt-get install -y pandoc

          diff_list=$(git diff --name-only ${GITHUB_EVENT_BEFORE}..HEAD)

          mkdir html
          html_dir=html
          for file in $diff_list; do
            if [[ ${file} != *.md ]]; then
              continue
            fi
            
            # md -> html変換
            html_file=$html_dir/$(basename "${file}" .md).html
            pandoc -f markdown -t html "${file}" > ${html_file}

            # img パス置換
            # ./README-images
            # ↓
            # https://github.com/d4y8/learning-labs/blob/main/.github/workflows/README-images
            sed -i 's/\.\/README-images/https:\/\/github\.com\/d4y8\/learning-labs\/blob\/main\/\.github\/workflows\/README-images/g' ${html_file}

            cat ${html_file}
          done

      - name: Set up authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Call Blogger API
        env: 
          BLOG_ID: ${{ secrets.BLOG_ID }}
        run: |
          python .github/scripts/blog_post.py
