name: Publish to Google Blogger

on:
  push:
    branches: [ main ]

jobs:
  call-blogger-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.1'
      - name: Install dependencies
        run: pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib
      - name: Set up authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Git Diff
        run: |
          diff_list=$(git diff --name-only ${{ github.event.before }}..HEAD)
          echo $diff_list
      - name: Call Blogger API
        env: 
          BLOG_ID: ${{ secrets.BLOG_ID }}
        run: |
          python .github/script/test.py
